import Head from 'next/head'
import styles from '/styles/Home.module.css'
import Link from 'next/link'
import Image from 'next/image'

const Navbar = () => {
    return(  <>
    <div className={styles.container}>
      <Head>
        <title>E-summit 22 | IIT Roorkee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <nav className={styles.navbar}>
         <ul>
         <Image
         src="/Esummitlogofinal.jpg"
          alt="logo image"
         width={"200"}
         height={"40"}
         />    
        
         <Link href='/home'><li><a>HOME</a></li></Link>
         <Link href='/teams'><li><a>TEAMS</a></li></Link>
          <Link href='/events'><li><a>EVENTS</a></li></Link>
          <Link href='/speakers'><li><a>SPEAKERS</a></li></Link>
          <Link href='/faq'><li><a>FAQ</a></li></Link>
          
          <li className={styles.nav_right}> LOG IN </li>
          <li className={styles.nav_right1}>or</li>
          <li className={styles.nav_right2}>REGISTER</li>

        </ul>
        </nav>
        </div>
        </>
        
    )
}
export default  Navbar;