import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>E-summit 22 | IIT Roorkee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.navbar}>
        <ul>
         <Link href='/home'><li>HOME</li></Link>
         <Link href='/teams'><li><a>TEAMS</a></li></Link>
          <Link href='/events'><li>EVENTS</li></Link>
          <Link href='/speakers'><li>SPEAKERS</li></Link>
          <Link href='/faq'><li>FAQ</li></Link>
          <li> Login or</li>
          <li>Register</li>
        </ul>
      </nav>

      </div>
  )
}
